### ISSUE TITLE
[help]Post install.

### ISSUE THREAD

**Issue by bombardinotungtung** [wadimw/dell-7577-hackintosh#3]
i havent installed mac os for a long time .if i remember correctly these are the steps.
1)write image to usb 
2)copy clover folder to usb
3)install and run post install commands
4)install clover and copy efi again

am i right? also i have same hardware but intel i7 7700hq and 1050ti.will it be problem ? or dsdt will be same

**Comment by wadimw** [comment]
That's basically it, yes. In general for each laptop you may need some adjustments even if it's the same model, but there is a good chance this will work for you to, especially since I have not patched whole dsdt but used hotpatching instead.

**Comment by baritonerosecandytea** [comment]
Thanks for your effort.Catalina works perfectly .i just dragged clover folder.and thats it.thanj you so much
